//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sozluk.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public short Id { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string Mail { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAdmin { get; set; }
    }
}
