//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sozluk.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public Nullable<short> LanguageID { get; set; }
        public string Translation { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
